import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "計數器: \{root.counter}";
        }

        Button {
            text: "增加值";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}